spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: 11111111
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: points

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



